FROM node:alpine as builder

WORKDIR /usr/src/app
COPY node_modules node_modules
COPY package.json .
COPY package-lock.json .
COPY public public
COPY src src

RUN npm run build


FROM scratch as runtime
VOLUME /usr/app
COPY --from=builder /usr/src/app/build /app
CMD ["noop"]
