version: 2
jobs:
  server:
    docker:
      - image: circleci/buildpack-deps
    steps:
      - checkout
      - setup_remote_docker
      - run: make package-server
  client:
    docker:
      - image: circleci/buildpack-deps
    steps:
      - checkout
      - setup_remote_docker
      - run: make package-client
workflows:
  version: 2
  build:
    jobs:
      - server
      - client
