version: 2
jobs:
  server:
    docker:
      - image: circleci/buildpack-deps
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: make package-server
      - run: make publish-server
workflows:
  version: 2
  build:
    jobs:
      - server
